#!/usr/bin/env python
"""Use livereload to serve documentation locally.
"""
from livereload import Server, shell

if __name__ == "__main__":

    server = Server()
    server.watch('./', shell('make html', cwd='.'))
    server.serve(root='_build/html') # Defaults to port 5500
